## p. 66

In [1]:
import numpy as np

In [2]:
a = np.matrix([[3,2],
               [1,4]])
np.linalg.inv(a)

matrix([[ 0.4, -0.2],
        [-0.1,  0.3]])

In [3]:
b = np.matrix([[-1,4],
               [0,1]])
np.linalg.inv(b)

matrix([[-1.,  4.],
        [ 0.,  1.]])

In [4]:
c = np.matrix([[-5,1],
               [2,1]])
np.linalg.inv(c)

matrix([[-0.14285714,  0.14285714],
        [ 0.28571429,  0.71428571]])

In [6]:
d = np.matrix([[4,1],
               [2,3]])
d_inv = np.linalg.inv(d)
e = np.matrix([[1,3],
               [-1,1]])
A = np.dot(d_inv,e)
A

matrix([[ 0.4,  0.8],
        [-0.6, -0.2]])

なぜ逆行列を左からかけるのか？ 
- dA = eなのであって，d_inv*dA = ?だから

In [8]:
np.dot(d_inv,d)

matrix([[ 1.00000000e+00, -5.55111512e-17],
        [ 0.00000000e+00,  1.00000000e+00]])

In [17]:
f = np.matrix([[-1,1],
               [1,4]])
f_inv = np.linalg.inv(f)
print(f_inv)
g = np.matrix([[3,2],
               [1,-1]])
A2 = np.dot(g,f_inv)
A2

[[-0.8  0.2]
 [ 0.2  0.2]]


matrix([[-2.,  1.],
        [-1.,  0.]])

In [20]:
h = np.matrix([[1/2,3/2],
               [-1/2,5/2]])
h_inv = np.linalg.inv(h)
i = np.matrix([[1/4,2/4],
               [2/4,5/4]])
np.dot(h_inv,i)

matrix([[-0.0625, -0.3125],
        [ 0.1875,  0.4375]])