# マンガ　線形代数入門　はじめての人でも楽しく学べる 練習問題

## p. 38

In [3]:
import numpy as np

In [14]:
menu = np.matrix([[360,240],
                  [168,206]])
half = menu * 1/2
half

matrix([[180., 120.],
        [ 84., 103.]])

In [17]:
gelato = np.matrix([[100,100],
                   [72,72]])
menu + gelato

matrix([[460, 340],
        [240, 278]])

In [18]:
half + gelato

matrix([[280., 220.],
        [156., 175.]])

## p. 39

In [20]:
a = np.matrix([[400,300],
               [15,6]])
b = np.array([5,4])
np.dot(a,b)

matrix([[3200,   99]])

In [22]:
c = np.matrix([[3,-1],
               [-2,3]])
d = np.array([6,2])
e = np.matrix([[-3,2],
               [-1,3]])
f = np.array([2,-3])
np.dot(c,d)+np.dot(e,f)

matrix([[  4, -17]])

In [23]:
g = np.matrix([[3,6],
               [2,4]])
h = np.matrix([[-1,2],
               [3,-1]])
np.dot(g,h)

matrix([[15,  0],
        [10,  0]])

In [25]:
i = np.matrix([[1,0],
               [3,5]])
j = np.matrix([[4,3],
               [-1,2]])
k = np.matrix([[0,2],
               [8,1]])
l = np.matrix([[3,7],
               [-2,-1]])
np.dot(i,j)-np.dot(k,l)


matrix([[  8,   5],
        [-15, -36]])