## p. 230

(1)

In [1]:
import numpy as np

In [5]:
A = np.array([[3,2,0],
              [1,1,2],
              [2,6,1]])
detA = np.linalg.det(A)
detA
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.40740741,  0.07407407, -0.14814815],
       [-0.11111111, -0.11111111,  0.22222222],
       [-0.14814815,  0.51851852, -0.03703704]])

In [6]:
A = np.array([[3,-1,-1],
              [-6,2,2],
              [-3,1,1]])
detA = np.linalg.det(A)
detA

0.0

In [9]:
A = np.array([[-1,1,3],
              [3,2,-2],
              [2,3,1]])
detA = np.linalg.det(A)
detA
np.linalg.inv(A)

array([[ 1.80143985e+15,  1.80143985e+15, -1.80143985e+15],
       [-1.57625987e+15, -1.57625987e+15,  1.57625987e+15],
       [ 1.12589991e+15,  1.12589991e+15, -1.12589991e+15]])

In [11]:
A = np.array([[1,0,-1],
              [1,1,0],
              [0,-1,3]])
detA = np.linalg.det(A)
detA
np.linalg.inv(A)

array([[ 0.75,  0.25,  0.25],
       [-0.75,  0.75, -0.25],
       [-0.25,  0.25,  0.25]])